### ISSUE TITLE
Rails 2.3 Nested Forms

### ISSUE THREAD

**Issue by kevinansfield** [ryanfelton/textile-editor-helper#1]
When using the textile_editor helper method in a Rails 2.3 nested form, the ID attribute placed in the generated initialisation script is incorrect. Eg:

Plugin generates: TextileEditor.initialize('user[profile_attributes]_bio', 'extended');

Should generate: TextileEditor.initialize('user_profile_attributes_bio', 'extended');

Note: This is using jQuery framework. Haven't tested with Prototype

**Comment by rurounijones** [comment]
Confirmed with prototype.

```
textarea cols="40" id="topic_posts_attributes_0_body"  name="topic[posts_attributes][0][body]" rows="20"

TextileEditor.initialize('topic[posts_attributes][0]_body', 'extended');
```

**Comment by rurounijones** [comment]
I suppose a work around would be to gsub [ and ] to _ and then squeeze the result.

**Comment by koszta** [comment]
using editor_id.gsub(/][|]_|[|]/, '_') should fix this

**Comment by kevinansfield** [comment]
Closing as I'm cleaning up my own issues and this gem appears unmaintained. Feel free to reopen if needed, and thank you for creating textile-editor-helper! 😄
