### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by meesern** [ryanfelton/textile-editor-helper#2]
I may be missing something but how do I install this.   Is it a gem of a plugin?  I have the git address and know that I have to do something with it before I can run rake as in the readme, but what?

**Comment by ryanfelton** [comment]
Yes, it's a plugin that is installed via 
script/plugin install git@github.com:felttippin/textile-editor-helper.git

From there, see the instructions labeled "To use Textile Editor Helper"

**Comment by meesern** [comment]
Thanks.  When I tried that I got permission denied :-(

The slate branch did install ok.
